### ISSUE TITLE
Changes in readme.md

### ISSUE THREAD

**Issue by Dhruvanshu-Joshi** [aditidhu/IMAGE-INPAINTING#2]
https://github.com/aditidhu/IMAGE-INPAINTING/blob/93df7939842890e46412a9ad23673c11264e1bb0/README.md?plain=1#L83

Here instead of copy the code, use 'run the notebook'.

https://github.com/aditidhu/IMAGE-INPAINTING/blob/93df7939842890e46412a9ad23673c11264e1bb0/README.md?plain=1#L89

Here instead of libraries in requirements.txt, add all the library names along with version.

This holds for everywhere the above format is repeated.

https://github.com/aditidhu/IMAGE-INPAINTING/blob/93df7939842890e46412a9ad23673c11264e1bb0/README.md?plain=1#L100C1-L100C1

Here instead of copy the code, use run the final.py or whatever is the name of your .py script and tell users to input the correct path for image, mask and fmm method.

https://github.com/aditidhu/IMAGE-INPAINTING/blob/93df7939842890e46412a9ad23673c11264e1bb0/README.md?plain=1#L135

Do as directed.

https://github.com/aditidhu/IMAGE-INPAINTING/blob/93df7939842890e46412a9ad23673c11264e1bb0/README.md?plain=1#L143-L149

Add reference paper link.

**Comment by aditidhu** [comment]
resolved
